### ISSUE TITLE
List of scikits page is broken

### ISSUE THREAD

**Issue by cladmi** [scipy/scipy.org#170]
When accessing http://scikits.appspot.com/scikits I get

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 715, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/s~scikits-hrd/1.387270795685241486/scikits.py", line 207, in get
    packages = sorted(Package.packages().values())
  File "/base/data/home/apps/s~scikits-hrd/1.387270795685241486/scikits.py", line 326, in packages
    results = server.search(dict(name="scikit"))
  File "/base/data/home/runtimes/python/python_dist/lib/python2.5/xmlrpclib.py", line 1147, in __call__
    return self.__send(self.__name, args)
  File "/base/data/home/runtimes/python/python_dist/lib/python2.5/xmlrpclib.py", line 1437, in __request
    verbose=self.__verbose
  File "/base/data/home/apps/s~scikits-hrd/1.387270795685241486/tools.py", line 230, in request
    response.headers)
ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 >
```

**Comment by takluyver** [comment]
I think this is where you want to report that: https://bitbucket.org/janto/scikits_index

**Comment by pv** [comment]
cc @stefanv @janto

**Comment by pv** [comment]
https://bitbucket.org/janto/scikits_index/issues/7/protocolerror-for-pypipythonorg-pypi-403

**Comment by pv** [comment]
Was fixed
