### ISSUE TITLE
ndimage missing reverse attribute

### ISSUE THREAD

**Issue by Jee-Bee** [scipy/scipy.org#227]
I know that the tutorials  are not stricly the website but on the devdocs there are no possibilities to add an issue. So i do it here...

I am doing the ndimage tutorial with python 3. in the following script i get an error:

```
>>> a = np.arange(12).reshape(3,4)
>>>
>>> class fnc_class:
...     def __init__(self, shape):
...         # store the shape:
...         self.shape = shape
...         # initialize the coordinates:
...         self.coordinates = [0] * len(shape)
...
...     def filter(self, buffer):
...         result = (buffer * np.array([1, 3])).sum()
...         print self.coordinates
...         # calculate the next coordinates:
...         axes = range(len(self.shape))
...         axes.reverse()
...         for jj in axes:
...             if self.coordinates[jj] < self.shape[jj] - 1:
...                 self.coordinates[jj] += 1
...                 break
...             else:
...                 self.coordinates[jj] = 0
...         return result
...
>>> fnc = fnc_class(shape = (3,4))
>>> generic_filter(a, fnc.filter, footprint = [[1, 0], [0, 1]])
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-115-c77045afae13>", line 2, in <module>
    generic_filter(a, fnc.filter, footprint=[[1, 0], [0, 1]])
  File "/usr/local/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 1486, in generic_filter
    cval, origins, extra_arguments, extra_keywords)
  File "<ipython-input-108-a00f46f1b224>", line 14, in filter
    axes.reverse()
AttributeError: 'range' object has no attribute 'reverse'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2879, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'
```

Since didn't know what should happens within reverse function i'm not able to fix it. I only can show where the line is what goes wrong....
on this line it goes wrong
[https://github.com/scipy/devdocs/blob/gh-pages/tutorial/ndimage.html#L663]()

**Comment by pv** [comment]
Correct issue tracker: https://github.com/scipy/scipy/ (it's scipy documentation)
